# Generated by Django 3.2.17 on 2023-02-11 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lenguage_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='metadata_id',
        ),
        migrations.AddField(
            model_name='metadata',
            name='content_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.content'),
        ),
    ]
