# Generated by Django 3.2.17 on 2023-02-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230211_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='parent_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='picture_url',
            field=models.URLField(max_length=255),
        ),
    ]
