# Generated by Django 3.2.17 on 2023-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_content_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='groups',
            field=models.ManyToManyField(related_name='channels', to='api.Group'),
        ),
    ]
